### ISSUE TITLE
Module '"@liaoliaots/nestjs-redis"' has no exported member 'InjectRedis'

### ISSUE THREAD

**Issue by maheshupasani** [DevAngsy/nestjs-redis#553]
After upgrading version 9 to version 10, existing code is not working and the decorators are removed in new version 10.

src/databases/redis.service.ts:1:10 - error TS2305: Module '"@liaoliaots/nestjs-redis"' has no exported member 'InjectRedis'.
1 import { InjectRedis } from '@liaoliaots/nestjs-redis';
           ~~~~~~~~~~~

export class RedisService {
  constructor(@InjectRedis() private readonly redisClient: Redis) { }
}


### Steps to reproduce

Below is implementation that is working in v9.
src/databases/redis.service.ts:1:10 - error TS2305: Module '"@liaoliaots/nestjs-redis"' has no exported member 'InjectRedis'.
1 import { InjectRedis } from '@liaoliaots/nestjs-redis';
           ~~~~~~~~~~~

export class RedisService {
  constructor(@InjectRedis() private readonly redisClient: Redis) { }
}

### Expected behavior

It should work after upgrading it to v10 from v9

### Environment

- OS: [e.g. Arch Linux]
- Other details that you think may affect.

**Comment by Scalahansolo** [comment]
Read the v10 update release notes. `InjectRedis` was removed.

**Comment by liaoliaots** [comment]
`InjectRedis` has some issues which would lead to inconsistent behavior in production environments, so it has been removed for now.

**Comment by kameshpal** [comment]
what is the alternate approach to mitigate in v10 ?

**Comment by Stanback** [comment]
@kameshpal As far as I know you would replace something like this:

```ts
import { Redis } from 'ioredis';

// ...

  constructor(
    // ...

    @InjectRedis()
    private readonly redis: Redis,

   // ...
) {
```

with this:

```ts
import { RedisService } from '@liaoliaots/nestjs-redis';

// ...

  constructor(
    // ...

    private readonly redisService: RedisService, // Or ClusterService depending on your situation

   // ...
) {
```

Then update your usage:

```ts
// Instead of this:

this.redis.setnx(...) // or whatever operation you want

// You'll do this:

this.redisService.getOrThrow().setnx(...) // there's also a getOrNil(), in either case, it's up to you to figure out error handling
```
